/*
 * Hotel Booking System API
 * API for managing hotels and rooms (Hotel & Room entities).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.81
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Hotel model module.
 * @module model/Hotel
 * @version 1.0.0
 */
export default class Hotel {
  /**
   * Constructs a new <code>Hotel</code>.
   * @alias module:model/Hotel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Hotel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Hotel} obj Optional instance to populate.
   * @return {module:model/Hotel} The populated <code>Hotel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Hotel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('stars'))
        obj.stars = ApiClient.convertToType(data['stars'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Hotel.prototype.id = undefined;

/**
 * @member {String} name
 */
Hotel.prototype.name = undefined;

/**
 * @member {String} city
 */
Hotel.prototype.city = undefined;

/**
 * @member {String} address
 */
Hotel.prototype.address = undefined;

/**
 * @member {Number} stars
 */
Hotel.prototype.stars = undefined;

