/*
 * Hotel Booking System API
 * API for managing hotels and rooms (Hotel & Room entities).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.81
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The HotelInput model module.
 * @module model/HotelInput
 * @version 1.0.0
 */
export default class HotelInput {
  /**
   * Constructs a new <code>HotelInput</code>.
   * @alias module:model/HotelInput
   * @class
   * @param name {String} 
   * @param city {String} 
   * @param address {String} 
   * @param stars {Number} 
   */
  constructor(name, city, address, stars) {
    this.name = name;
    this.city = city;
    this.address = address;
    this.stars = stars;
  }

  /**
   * Constructs a <code>HotelInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HotelInput} obj Optional instance to populate.
   * @return {module:model/HotelInput} The populated <code>HotelInput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HotelInput();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('stars'))
        obj.stars = ApiClient.convertToType(data['stars'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
HotelInput.prototype.name = undefined;

/**
 * @member {String} city
 */
HotelInput.prototype.city = undefined;

/**
 * @member {String} address
 */
HotelInput.prototype.address = undefined;

/**
 * @member {Number} stars
 */
HotelInput.prototype.stars = undefined;

