/*
 * Hotel Booking System API
 * API for managing hotels and rooms (Hotel & Room entities).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.81
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RoomInput model module.
 * @module model/RoomInput
 * @version 1.0.0
 */
export default class RoomInput {
  /**
   * Constructs a new <code>RoomInput</code>.
   * @alias module:model/RoomInput
   * @class
   * @param roomNumber {String} 
   * @param type {module:model/RoomInput.TypeEnum} 
   * @param pricePerNight {Number} 
   */
  constructor(roomNumber, type, pricePerNight) {
    this.roomNumber = roomNumber;
    this.type = type;
    this.pricePerNight = pricePerNight;
  }

  /**
   * Constructs a <code>RoomInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RoomInput} obj Optional instance to populate.
   * @return {module:model/RoomInput} The populated <code>RoomInput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RoomInput();
      if (data.hasOwnProperty('roomNumber'))
        obj.roomNumber = ApiClient.convertToType(data['roomNumber'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('pricePerNight'))
        obj.pricePerNight = ApiClient.convertToType(data['pricePerNight'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} roomNumber
 */
RoomInput.prototype.roomNumber = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
RoomInput.TypeEnum = {
  /**
   * value: "Single"
   * @const
   */
  single: "Single",

  /**
   * value: "Double"
   * @const
   */
  _double: "Double",

  /**
   * value: "Suite"
   * @const
   */
  suite: "Suite"
};
/**
 * @member {module:model/RoomInput.TypeEnum} type
 */
RoomInput.prototype.type = undefined;

/**
 * @member {Number} pricePerNight
 */
RoomInput.prototype.pricePerNight = undefined;

