/*
 * Hotel Booking System API
 * API for managing hotels and rooms (Hotel & Room entities).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.81
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Room model module.
 * @module model/Room
 * @version 1.0.0
 */
export default class Room {
  /**
   * Constructs a new <code>Room</code>.
   * @alias module:model/Room
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Room</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Room} obj Optional instance to populate.
   * @return {module:model/Room} The populated <code>Room</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Room();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('hotelId'))
        obj.hotelId = ApiClient.convertToType(data['hotelId'], 'String');
      if (data.hasOwnProperty('roomNumber'))
        obj.roomNumber = ApiClient.convertToType(data['roomNumber'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('pricePerNight'))
        obj.pricePerNight = ApiClient.convertToType(data['pricePerNight'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Room.prototype.id = undefined;

/**
 * @member {String} hotelId
 */
Room.prototype.hotelId = undefined;

/**
 * @member {String} roomNumber
 */
Room.prototype.roomNumber = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Room.TypeEnum = {
  /**
   * value: "Single"
   * @const
   */
  single: "Single",

  /**
   * value: "Double"
   * @const
   */
  _double: "Double",

  /**
   * value: "Suite"
   * @const
   */
  suite: "Suite"
};
/**
 * @member {module:model/Room.TypeEnum} type
 */
Room.prototype.type = undefined;

/**
 * @member {Number} pricePerNight
 */
Room.prototype.pricePerNight = undefined;

