/*
 * Hotel Booking System API
 * API for managing hotels and rooms (Hotel & Room entities).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.81
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HotelBookingSystemApi);
  }
}(this, function(expect, HotelBookingSystemApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('HotelInput', function() {
      beforeEach(function() {
        instance = new HotelBookingSystemApi.HotelInput();
      });

      it('should create an instance of HotelInput', function() {
        // TODO: update the code to test HotelInput
        expect(instance).to.be.a(HotelBookingSystemApi.HotelInput);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property city (base name: "city")', function() {
        // TODO: update the code to test the property city
        expect(instance).to.have.property('city');
        // expect(instance.city).to.be(expectedValueLiteral);
      });

      it('should have the property address (base name: "address")', function() {
        // TODO: update the code to test the property address
        expect(instance).to.have.property('address');
        // expect(instance.address).to.be(expectedValueLiteral);
      });

      it('should have the property stars (base name: "stars")', function() {
        // TODO: update the code to test the property stars
        expect(instance).to.have.property('stars');
        // expect(instance.stars).to.be(expectedValueLiteral);
      });

    });
  });

}));
