/*
 * Hotel Booking System API
 * API for managing hotels and rooms (Hotel & Room entities).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.81
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HotelBookingSystemApi);
  }
}(this, function(expect, HotelBookingSystemApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RoomInput', function() {
      beforeEach(function() {
        instance = new HotelBookingSystemApi.RoomInput();
      });

      it('should create an instance of RoomInput', function() {
        // TODO: update the code to test RoomInput
        expect(instance).to.be.a(HotelBookingSystemApi.RoomInput);
      });

      it('should have the property roomNumber (base name: "roomNumber")', function() {
        // TODO: update the code to test the property roomNumber
        expect(instance).to.have.property('roomNumber');
        // expect(instance.roomNumber).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property pricePerNight (base name: "pricePerNight")', function() {
        // TODO: update the code to test the property pricePerNight
        expect(instance).to.have.property('pricePerNight');
        // expect(instance.pricePerNight).to.be(expectedValueLiteral);
      });

    });
  });

}));
