/*
 * Hotel Booking System API
 * API for managing hotels and rooms (Hotel & Room entities).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.81
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Hotel from './model/Hotel';
import HotelInput from './model/HotelInput';
import Room from './model/Room';
import RoomInput from './model/RoomInput';
import DefaultApi from './api/DefaultApi';

/**
* API_for_managing_hotels_and_rooms__Hotel__Room_entities_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var HotelBookingSystemApi = require('index'); // See note below*.
* var xxxSvc = new HotelBookingSystemApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new HotelBookingSystemApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new HotelBookingSystemApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new HotelBookingSystemApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Hotel model constructor.
     * @property {module:model/Hotel}
     */
    Hotel,

    /**
     * The HotelInput model constructor.
     * @property {module:model/HotelInput}
     */
    HotelInput,

    /**
     * The Room model constructor.
     * @property {module:model/Room}
     */
    Room,

    /**
     * The RoomInput model constructor.
     * @property {module:model/RoomInput}
     */
    RoomInput,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
