/*
 * Hotel Booking System API
 * API for managing hotels and rooms (Hotel & Room entities).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.81
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HotelBookingSystemApi);
  }
}(this, function(expect, HotelBookingSystemApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HotelBookingSystemApi.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('hotelsGet', function() {
        it('should call hotelsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for hotelsGet call and complete the assertions
          /*
          var opts = {};

          instance.hotelsGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(HotelBookingSystemApi.Hotel);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('hotelsHotelIdRoomsGet', function() {
        it('should call hotelsHotelIdRoomsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for hotelsHotelIdRoomsGet call and complete the assertions
          /*

          instance.hotelsHotelIdRoomsGet(hotelId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(HotelBookingSystemApi.Room);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('hotelsHotelIdRoomsPost', function() {
        it('should call hotelsHotelIdRoomsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for hotelsHotelIdRoomsPost call
          /*

          instance.hotelsHotelIdRoomsPost(body, hotelId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('hotelsIdDelete', function() {
        it('should call hotelsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for hotelsIdDelete call
          /*

          instance.hotelsIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('hotelsIdGet', function() {
        it('should call hotelsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for hotelsIdGet call and complete the assertions
          /*

          instance.hotelsIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HotelBookingSystemApi.Hotel);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('hotelsIdPut', function() {
        it('should call hotelsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for hotelsIdPut call
          /*

          instance.hotelsIdPut(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('hotelsPost', function() {
        it('should call hotelsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for hotelsPost call and complete the assertions
          /*

          instance.hotelsPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HotelBookingSystemApi.Hotel);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('roomsIdDelete', function() {
        it('should call roomsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for roomsIdDelete call
          /*

          instance.roomsIdDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('roomsIdGet', function() {
        it('should call roomsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for roomsIdGet call
          /*

          instance.roomsIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('roomsIdPut', function() {
        it('should call roomsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for roomsIdPut call
          /*

          instance.roomsIdPut(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
